version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: es01
    ports:
      - "9200:9200"
    networks:
      - elk-network
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Adjust memory settings as needed
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    container_name: kib01
    ports:
      - "5601:5601"
    networks:
      - elk-network
    depends_on:
      - elasticsearch
      
  alpha-data-service:
    image: alpha-data-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - elk-network
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # Bind mount logstash.conf
    ports:
      - "5044:5044" # Port for Logstash input
    networks:
      - elk-network
    depends_on:
      - elasticsearch

networks:
  elk-network:
    external: true